#from discord_bot.channel_types.base_object import discord_feed_service as insight_feed_service_base
from discord_bot.channel_types.capRadar import capRadar as insight_capRadar
from discord_bot.channel_types.direct_message import discord_text_nofeed_exist as insight_directMessage
from discord_bot.channel_types.nofeed_text import discord_text_nofeed_exist as insight_textChannel_NoFeed