#!/bin/bash
INSIGHT_VERSION_PATCH="1.7.0"
INSIGHT_VERSION_MINOR=$(echo "$INSIGHT_VERSION_PATCH" | sed 's/.[0-9]$//')

docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ../../

if [[ "$SOURCE_BRANCH" == "master" ]]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:$INSIGHT_VERSION_PATCH
  docker tag $IMAGE_NAME $DOCKER_REPO:$INSIGHT_VERSION_MINOR
fi

if [[ "$SOURCE_BRANCH" == "development" ]]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:"$INSIGHT_VERSION_PATCH-dev"
  docker tag $IMAGE_NAME $DOCKER_REPO:"$INSIGHT_VERSION_MINOR-dev"
fi


