#!/bin/bash
INSIGHT_VERSION_PATCH="1.7.0"
INSIGHT_VERSION_MINOR=$(echo "$INSIGHT_VERSION_PATCH" | sed 's/.[0-9]$//')

docker push $IMAGE_NAME

if [[ "$SOURCE_BRANCH" == "master" ]]; then
  docker push $DOCKER_REPO:$INSIGHT_VERSION_PATCH
  docker push $DOCKER_REPO:$INSIGHT_VERSION_MINOR
fi

if [[ "$SOURCE_BRANCH" == "development" ]]; then
  docker push $DOCKER_REPO:"$INSIGHT_VERSION_PATCH-dev"
  docker push $DOCKER_REPO:"$INSIGHT_VERSION_MINOR-dev"
fi

