INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000001, 'Derelik', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000002, 'The Forge', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000003, 'Vale of the Silent', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000004, 'UUA-F4', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000005, 'Detorid', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000006, 'Wicked Creek', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000007, 'Cache', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000008, 'Scalding Pass', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000009, 'Insmother', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000010, 'Tribute', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000011, 'Great Wildlands', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000012, 'Curse', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000013, 'Malpais', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000014, 'Catch', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000015, 'Venal', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000016, 'Lonetrek', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000017, 'J7HZ-F', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000018, 'The Spire', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000019, 'A821-A', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000020, 'Tash-Murkon', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000021, 'Outer Passage', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000022, 'Stain', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000023, 'Pure Blind', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000025, 'Immensea', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000027, 'Etherium Reach', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000028, 'Molden Heath', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000029, 'Geminate', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000030, 'Heimatar', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000031, 'Impass', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000032, 'Sinq Laison', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000033, 'The Citadel', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000034, 'The Kalevala Expanse', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000035, 'Deklein', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000036, 'Devoid', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000037, 'Everyshore', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000038, 'The Bleak Lands', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000039, 'Esoteria', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000040, 'Oasa', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000041, 'Syndicate', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000042, 'Metropolis', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000043, 'Domain', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000044, 'Solitude', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000045, 'Tenal', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000046, 'Fade', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000047, 'Providence', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000048, 'Placid', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000049, 'Khanid', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000050, 'Querious', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000051, 'Cloud Ring', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000052, 'Kador', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000053, 'Cobalt Edge', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000054, 'Aridia', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000055, 'Branch', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000056, 'Feythabolis', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000057, 'Outer Ring', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000058, 'Fountain', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000059, 'Paragon Soul', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000060, 'Delve', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000061, 'Tenerifis', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000062, 'Omist', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000063, 'Period Basis', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000064, 'Essence', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000065, 'Kor-Azor', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000066, 'Perrigen Falls', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000067, 'Genesis', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000068, 'Verge Vendor', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (10000069, 'Black Rise', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000001, 'A-R00001', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000002, 'A-R00002', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000003, 'A-R00003', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000004, 'B-R00004', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000005, 'B-R00005', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000006, 'B-R00006', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000007, 'B-R00007', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000008, 'B-R00008', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000009, 'C-R00009', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000010, 'C-R00010', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000011, 'C-R00011', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000012, 'C-R00012', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000013, 'C-R00013', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000014, 'C-R00014', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000015, 'C-R00015', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000016, 'D-R00016', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000017, 'D-R00017', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000018, 'D-R00018', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000019, 'D-R00019', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000020, 'D-R00020', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000021, 'D-R00021', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000022, 'D-R00022', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000023, 'D-R00023', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000024, 'E-R00024', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000025, 'E-R00025', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000026, 'E-R00026', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000027, 'E-R00027', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000028, 'E-R00028', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000029, 'E-R00029', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000030, 'F-R00030', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000031, 'G-R00031', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000032, 'H-R00032', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (11000033, 'K-R00033', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (12000001, 'ADR01', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (12000002, 'ADR02', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (12000003, 'ADR03', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (12000004, 'ADR04', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (12000005, 'ADR05', null, null, null, null);
INSERT INTO regions (region_id, name, description, api_ETag, api_Expires, api_Last_Modified) VALUES (13000001, 'PR-01', null, null, null, null);