from Insight.discord_bot.OptionLogic.EntityOptions.AddShipOption import AddShipOption
from Insight.discord_bot.OptionLogic.EntityOptions.RemoveShipOption import RemoveShipOption
from Insight.discord_bot.OptionLogic.EntityOptions.AddShipOptionWL import AddShipOptionWL
from Insight.discord_bot.OptionLogic.EntityOptions.RemoveShipOptionWL import RemoveShipOptionWL
from Insight.discord_bot.OptionLogic.EntityOptions.MinValueOption import MinValueOption
from Insight.discord_bot.OptionLogic.EntityOptions.MaxValueOption import MaxValueOption
