from .regions import Regions as tb_regions
from .constellations import Constellations as tb_constellations
from .systems import Systems as tb_systems
from .categories import Categories as tb_categories
from .groups import Groups as tb_groups
from .types import Types as tb_types
from .alliances import Alliances as tb_alliances
from .corporations import Corporations as tb_corporations
from .characters import Characters as tb_characters
from .victims import Victims as tb_victims
from .attackers import Attackers as tb_attackers
from .kills import Kills as tb_kills
from .mass_name_resolve import name_resolve as name_resolver
from .discord_base import discord_channel_base as tb_discord_base
from .discord_channels import Channels as tb_channels
from .discord_capRadar import CapRadar as tb_capRadar